# Generated by Django 3.1.6 on 2021-07-29 22:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('General', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Link', models.URLField(max_length=600)),
                ('Title', models.CharField(max_length=500)),
                ('fileid', models.CharField(max_length=100, null=True)),
                ('Thumbnail', models.URLField()),
                ('Description', models.TextField(default='No Description Available')),
                ('Is_free', models.BooleanField(default=True)),
                ('Published', models.BooleanField(default=False)),
                ('Created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('Updated_on', models.DateTimeField(default=datetime.datetime.now)),
                ('Like_count', models.IntegerField(default=0)),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.profile')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TextContent',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Feature_Image', models.ImageField(upload_to='article-post')),
                ('Headline', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=200, null=True)),
                ('Content', models.TextField(default='<h1>Not Added Yet</h1>')),
                ('fileid', models.CharField(max_length=100, null=True)),
                ('Is_free', models.BooleanField(default=True)),
                ('Created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('Updated_on', models.DateTimeField(default=datetime.datetime.now)),
                ('Published', models.BooleanField(default=False)),
                ('Like_count', models.IntegerField(default=0)),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.profile')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Message', models.TextField(default='No Messsage Available')),
                ('Link', models.CharField(default='/', max_length=100)),
                ('Send_to', models.ManyToManyField(blank=True, related_name='send_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageTrace',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Last_Image_Upload', models.CharField(default='', max_length=500)),
                ('fileid', models.CharField(max_length=100, null=True)),
                ('Current_Image', models.CharField(default='', max_length=500)),
                ('type', models.CharField(default='', max_length=500)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageContent',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Headline', models.CharField(max_length=50)),
                ('Image', models.URLField()),
                ('fileid', models.CharField(max_length=100, null=True)),
                ('Description', models.TextField()),
                ('Is_free', models.BooleanField(default=True)),
                ('Created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('Updated_on', models.DateTimeField(default=datetime.datetime.now)),
                ('Published', models.BooleanField(default=False)),
                ('Like_count', models.IntegerField(default=0)),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.profile')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
