# Generated by Django 3.1.6 on 2021-07-29 22:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('General', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('planName', models.CharField(max_length=100)),
                ('period', models.CharField(max_length=100)),
                ('interval', models.IntegerField(default=1)),
                ('amount', models.IntegerField(default=0)),
                ('description', models.TextField(default=' ')),
                ('planId', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('subscriptionId', models.CharField(default='', max_length=200, unique=True)),
                ('subscriptionLink', models.CharField(default='', max_length=200, unique=True)),
                ('planId', models.CharField(default='', max_length=500, null=True)),
                ('status', models.CharField(default='not created', max_length=100)),
                ('cancelled', models.BooleanField(default=False)),
                ('Creator_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_subscription', to='General.profile')),
                ('Customer_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_subscription', to='General.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPurchased',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('linkRefrence_id', models.CharField(default='', max_length=100)),
                ('payment_id', models.CharField(default='', max_length=100)),
                ('link_id', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('amount', models.FloatField(default=0)),
                ('Creator_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='General.profile')),
                ('Customer_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='General.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('order_id', models.CharField(max_length=200, null=True, unique=True)),
                ('payment_id', models.CharField(max_length=200, null=True, unique=True)),
                ('signature', models.CharField(max_length=500, null=True)),
                ('status', models.CharField(default='not created', max_length=100)),
                ('cancelled', models.BooleanField(default=False)),
                ('Creator_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_donation', to='General.profile')),
                ('Customer_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_donation', to='General.profile')),
            ],
        ),
    ]
