# Generated by Django 3.1.6 on 2021-07-29 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaAccounts',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('YouTube', models.CharField(blank=True, max_length=200, null=True)),
                ('Instagram', models.CharField(blank=True, max_length=200, null=True)),
                ('Facebook', models.CharField(blank=True, max_length=200, null=True)),
                ('Twitter', models.CharField(blank=True, max_length=200, null=True)),
                ('LinkedIn', models.CharField(blank=True, max_length=200, null=True)),
                ('Takatak', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_line', models.TextField(default='')),
                ('city', models.CharField(default='', max_length=200)),
                ('state', models.CharField(default='', max_length=200)),
                ('pin_code', models.CharField(default='', max_length=200)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('Gender', models.CharField(blank=True, max_length=30, null=True)),
                ('URL', models.URLField(null=True)),
                ('Country', models.CharField(blank=True, max_length=100, null=True)),
                ('UserType', models.CharField(blank=True, max_length=100, null=True)),
                ('Account_activated', models.BooleanField(default=False)),
                ('DateOfBirth', models.DateField(max_length=8)),
                ('Created_on', models.DateTimeField(auto_now_add=True)),
                ('Avatar', models.CharField(max_length=100)),
                ('fileid', models.CharField(max_length=100, null=True)),
                ('Phone_no', models.CharField(max_length=20)),
                ('Updated_on', models.DateTimeField(auto_now=True)),
                ('tab_order', models.TextField(blank=True, max_length=100, null=True)),
                ('Bio', models.TextField(default='No Bio')),
                ('Profile_incomplete', models.BooleanField(default=True)),
                ('otp_for_email', models.IntegerField(default=0, null=True)),
                ('otp_for_number', models.IntegerField(default=0, null=True)),
                ('Subscription_price', models.FloatField(default=0.0, null=True)),
                ('Payment_ID', models.CharField(max_length=50, null=True)),
                ('Revenue', models.FloatField(default=0, null=True)),
                ('total_donations', models.FloatField(default=0.0, null=True)),
                ('Why_to_subscribe', models.TextField(default='')),
                ('Following', models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('My_subscribers', models.ManyToManyField(blank=True, related_name='my_subscribers', to=settings.AUTH_USER_MODEL)),
                ('Subscribed', models.ManyToManyField(blank=True, related_name='subscribers', to=settings.AUTH_USER_MODEL)),
                ('my_followers', models.ManyToManyField(blank=True, related_name='my_followers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Post_id', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100, null=True)),
                ('Like_To', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Like_To', to='General.profile')),
                ('Like_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Like_by', to='General.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ImageTrack',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('LastImageUploaded', models.CharField(max_length=1000)),
                ('CurrentImage', models.CharField(max_length=1000)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bulletins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='General.profile')),
            ],
        ),
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Account_Number', models.CharField(max_length=100)),
                ('IFSC_Code', models.CharField(max_length=100)),
                ('Account_holder_name', models.CharField(max_length=100)),
                ('Street_Address', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Pincode', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AmountRedeemed',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Amount', models.FloatField(default=0)),
                ('Date', models.DateField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
