# Generated by Django 3.1.6 on 2021-08-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0002_auto_20210806_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='total_donations',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
